#! /usr/bin/env python

import rospy
from tf.transformations import euler_from_quaternion, quaternion_from_euler


roll = pitch = yaw = 0.0


def get_rotation (msg):
    global roll, pitch, yaw
    orientation_q = msg.quaternion
    orientation_list = [orientation_q.x, orientation_q.y, orientation_q.z, orientation_q.w]
    (roll, pitch, yaw) = euler_from_quaternion (orientation_list)
    print yaw

sub = rospy.Subscriber ('/heading', geometry_msgs, get_rotation)

r = rospy.Rate(1)

while not rospy.is_shutdown():
    quat = quaternion_from_euler (roll, pitch,yaw)
    print quat
    r.sleep()
